sudo: false
dist: trusty
language: python

addons:
  apt:
    packages:
    - python3
    - docker-ce

python:
- '3.6'

before_install:
- mkdir -p $HOME/.config/kubernaut
- openssl aes-256-cbc -K $encrypted_66c4a8345820_key -iv $encrypted_66c4a8345820_iv -in enc/kubernaut-config.json -out $HOME/.config/kubernaut/config.json -d

install:
- pip install -r dev-requirements.txt
- pip install -r ambassador/requirements.txt
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl

services:
- docker

env:
  global:
  - DOCKER_REGISTRY=-
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: pICW+jNQnKfTIi3cupJAzLe4If6FqvJ6OgAQIxfmnTxo/7w6EwzBh8zNqTJ60WCGXc/dqYpOtAYGZ/65hRR9HS9l3/8/wmZGeARoz/IR3dEbMpSQKRWTiF+J6UX24H2ol9u6vGa+JLgQuqJeTDdzGqk6h5sZ6H2a2dedOJ9Ns/QQlN/eCsxvYLHQmdzXtc+vlTAFfL902Y2AW7Ue0lqGdJlnzM9WxxX5amBxf9t73aY+pW4mqeysGPZfSlRdpkVAJd3TzYlC4fdJWYR5DGsHDXnXlQdQ7OcLC9Vpb4f5AAu4XPbdxpxW2oA4hxlV6ya1N+oDlZZo1RZiRugn7ecY7W3a6wI7HI91GbWLJe2BaCRW1TminmGZ+tSErz1AmGiOpiqjKeM7KvMwt2Kv5YpWkZcFy5ac0wSMP1qf9V6Kyn9INiohPCHiiy3vzy5a75fAdIVl9C/5x2n6SmNFf0bCO0RVDqqMBQvScjnAZDFZTKHhXDh8zHdQbhxTg0edKbJ+JimuzJYjvGLZkBVuQtW8XO/3kzycTsgzP8OgLH2Ww7qIP0jZpL4HAqIF5FePZ46u32iYqTmv2CokveMJJoCRK/tNKhB4a3Uc8wIHPPVAiTIme8LGJqDrpdzEKbRF7K3fB+qn2nypGfsdxXquNoNxs4/flBYfEt4sUWysvIpEtdY=
  - secure: Fnyqm81+1Ul5FEIjbNycC0KZkXGGbulf/pfXXoaIVbAsX3ZHB7Gl16E62Cm4Z+DUZ+LZyxfPLrgjnYhJDvCppu5JokaA4hJtO9NxDbN9lqltpGTvx+7Q+8pxOxmwNnesv3JaW28RFyR5rW2WC1wftwF1X7rm+cqcvL/YbGUQgJ4R9p/fDjHj4jHOhzUsDtD56+ryC0WlpmeByEHlWdVsxdiitus2zRdXUy55pcBmXfXwapHZEiKXk1DuMCAyINxhwCAAGxfXckRysXRpD8SP8IO1+/HZ7QuqNNJrFjskEhNqUdGQaxR2cUG8SDWpWelWVgfAWX/m9JiRCum2MqZOF7W5wKVLb0v+1TYW41+YzS+vIDAyEtC7zxXd/rOZxSnO6AwOTcwm6XIYffJuHD8Ir8JloRlb4UWIWVlfPGtS9UYBybmBp9YTUpHdOCUZi2PTockBxAGgG3wbuH2UVHbg720z9si5IPXKmt63FOqaI9D59Q8KQc9s25o6JdfqRq+gXHTs96A0AlkPvL6l2JSYJkTVTVbakIN2Mrv5K2XgyTvRGJCAnGJiIYBuLfeM1FrTAhh9dUWmCBEzqRJBum8sn1G+trqmyo4iSKd6iPby4/huw9firlC0kb9MNr23kxj36Swstq/K0FeEEual3uhlxxm9+vXOIgWA6bej1xRsIyw=
  - secure: F9oY34UDI8aXuZ9nb6z3/ltlqrNs4RUQHDZHa2YSFoq0r2Rn272Yg7oHfPh3deYNKxtUOBwwcpiC/7G9MqhkuLQEYhqY/KowidG6gOxCZdTDEVS10C4GDEMGj64URlUCS722tQYMIpniiB6LW2kEOOcEuzC6JsVxS7BowUEVk7Ly8BTzrgNuGFN2bSphRyrJyrS3Reo5a1YI3joUMzI29t7fegefTIHHONKhZpIE86wFRk11nwvJdt54Eu9dVFwiEiGW9L9SnG2ph4UiqN6z3iQFCQ8HNvnf+BvNasdMBR3f85DPnG/syqOcQrrE1e5T88UXRxyUwR2ty1ad+ZvQPggwsoFs1FmdJH04pGn0Tgpo/AHNe5c67tvDbw2W4jlFJgVI/keoFvQigSM2DUuL1i0v48TkZw8lgcfasRjtJi7iDTC4qqjyMLkY6y2TRTVDG/86qxK3No7vvJZajzntU3c6MUttiSDubaHL5RuklQ+7MjN5Dp1cD09L3Qqnm9KcjWzbNoyqriBO84VU4aJFF72jJ18qADX/UUj7cxi0ShY19BHX2Vrp3pPSNiePfO7okUrg5Wc4eD7u4eC+aUVHboEX35NhBnfj7/ASrsltIANYFmNarv3tvd67JIsm/Wz3pge6YOSV1pBr2IsGk5UVIXdJ/mm6GVWFlJ9PiELDBGc=
  - secure: BZ88D949X8MSsc7zAzosZThYkwOreO+TTJJ0b9WhNUNKooGx5cnhdpWOkBZapt+NafWGKPC0fVttiFhCA54Jv8RO2iAK9+zrGdmeoTg6gFQ82/GjJS+/Aeztff419Yc6huoe5sR+KsdRsO9X6h6M8EQlOw6PcDafq6y1xM5nYOrAvdT3YWFr7QwkaKnWkvU96abgNu/7kKIz13M48jtIDFTCJ0yZNRphDXMvP1e56I/Rz/KCCDdC7bymXRRiy+rXFusZN4icz/qsJpPY7ILpmWQQQb4Hf5vyqfWXX1KVVQgHY6Zny2yt1NI5WIAC4fX96pzk2ZETUYM/OrXsY8urkPZLEooIzx2Gu/vvgdmxP52LHJaJVtXYhPgcjJLb67Q9N/5zCP9YPWEMfFt8q8A77bEY54Agyrx9bOJS6yM7mSg7RS/FeG8XUFBLIaKXyR6CH6tfhh+KwZAbcU7lc/8wkmM7G4GbDAeLDWHJ2X8Ttvp2dgZT1C9wACsVecwsDlgRM3BypUEUpnipwBjpL0ki5LYIxCYTPWqfeUNRkzH5CxzijhEkhhOaYfk7VEga8RuCfck7BCi89yckZcD89k+x1XpLa/KeRdzeGJNbMXfVLjCY4d4T8hkE8HZAAXLBpeONeDNdUzelPT98Wh25eUAx0FBoGcSHGWeLjiCTHg3CBos=
  
script:
- bash scripts/travis-build.sh
